from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.database.connection import get_db
from app.schemas.responses import APIResponse, ActionRequest
from app.seed.scenario import run_seed
from app.investigation.engine import run_investigation_pipeline
from app.services import incident_service
from app.utils.logger import log

router = APIRouter(tags=["Incident Response & SOC"])

def format_response(data, status="success", meta=None) -> APIResponse:
    return APIResponse(status=status, data=data, meta=meta or {})

@router.get(
    "/health",
    response_model=APIResponse,
    summary="Health Check",
    description="Returns the operational status of the backend services."
)
def health_check():
    return format_response({
        "status": "ok",
        "database": "connected",
        "llm": "fallback",
        "version": "1.0.0"
    })

@router.get(
    "/version",
    response_model=APIResponse,
    summary="Version Info",
    description="Returns the current API build version and commit hash."
)
def get_version():
    return format_response({
        "version": "1.0.0",
        "build": "hackathon",
        "commit": "a1b2c3d"
    })

@router.get(
    "/dashboard", 
    response_model=APIResponse,
    summary="Get SOC Dashboard KPIs",
    description="Retrieves top-level KPIs including total events, raw alerts, and active incidents for the SOC dashboard."
)
def get_dashboard(db: Session = Depends(get_db)):
    try:
        stats = incident_service.get_dashboard_stats(db)
        return format_response({"kpis": stats})
    except Exception as e:
        log.error(f"Dashboard endpoint error: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")

@router.get(
    "/incidents",
    response_model=APIResponse,
    summary="List all incidents",
    description="Fetches a list of all correlated incidents generated by the investigation engine."
)
def list_incidents(db: Session = Depends(get_db)):
    try:
        data = incident_service.get_all_incidents(db)
        return format_response(data)
    except Exception as e:
        log.error(f"List incidents endpoint error: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")

@router.get(
    "/incidents/{id}",
    response_model=APIResponse,
    summary="Get detailed incident investigation",
    description="Fetches the pre-computed AI summary, evidence, and chronologically ordered timeline for a specific incident."
)
def get_incident(id: int, db: Session = Depends(get_db)):
    try:
        data = incident_service.get_incident_with_timeline(db, id)
        return format_response(data)
    except Exception as e:
        log.error(f"Get incident {id} endpoint error: {e}")
        if type(e).__name__ == "IncidentNotFound":
            raise HTTPException(status_code=404, detail="Incident not found")
        raise HTTPException(status_code=500, detail="Internal server error")

@router.post(
    "/incidents/{id}/action",
    response_model=APIResponse,
    summary="Take action on incident",
    description="Updates the status of an incident based on the SOC analyst's recommended action (e.g., 'freeze', 'escalate')."
)
def take_action(id: int, req: ActionRequest, db: Session = Depends(get_db)):
    try:
        incident = incident_service.take_action_on_incident(db, id, req.action)
        log.info(f"Action '{req.action}' taken on incident {id}")
        return format_response({"message": f"Action '{req.action}' recorded successfully", "status": incident.status})
    except Exception as e:
        if type(e).__name__ == "IncidentNotFound":
            raise HTTPException(status_code=404, detail="Incident not found")
        raise HTTPException(status_code=500, detail="Internal server error")

@router.post(
    "/demo/reset",
    response_model=APIResponse,
    summary="Reset & Seed Demo Data",
    description="Drops all existing data, seeds the database with a high-fidelity synthetic scenario, and runs the correlation engine to generate an incident."
)
def reset_demo(db: Session = Depends(get_db)):
    try:
        user_id = run_seed()
        run_investigation_pipeline(db, user_id)
        # Fetch the created incident to return stats
        incident = incident_service.get_all_incidents(db)[0]
        timeline_len = len(incident_service.get_incident_with_timeline(db, incident["id"])["timeline"])
        return format_response({
            "incident_created": True,
            "timeline_events": timeline_len,
            "confidence": incident["confidence"]
        })
    except Exception as e:
        log.error(f"Demo reset error: {e}")
        raise HTTPException(status_code=500, detail="Failed to reset demo")
