/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed-dim": "#b5c4ff",
        "inverse-surface": "#dde3ed",
        "tertiary": "#b5c4ff",
        "surface": "#0e141b",
        "surface-container": "#1a2027",
        "outline-variant": "#4d4635",
        "surface-container-high": "#242a32",
        "tertiary-container": "#89a3f9",
        "on-error-container": "#ffdad6",
        "surface-bright": "#343a42",
        "on-secondary-container": "#ff9a8d",
        "primary-fixed-dim": "#ecc246",
        "background": "#0e141b",
        "primary-container": "#c9a227",
        "surface-container-lowest": "#090f15",
        "on-background": "#dde3ed",
        "on-tertiary-fixed": "#00174d",
        "on-primary-fixed-variant": "#584400",
        "surface-variant": "#2f353d",
        "on-primary-fixed": "#241a00",
        "on-secondary": "#690004",
        "secondary-fixed": "#ffdad5",
        "on-secondary-fixed-variant": "#8f100f",
        "secondary-fixed-dim": "#ffb4aa",
        "surface-tint": "#ecc246",
        "secondary-container": "#8f100f",
        "surface-container-highest": "#2f353d",
        "primary-fixed": "#ffe08e",
        "on-secondary-fixed": "#410001",
        "surface-dim": "#0e141b",
        "on-tertiary": "#01297a",
        "on-error": "#690005",
        "on-tertiary-container": "#163686",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-primary": "#3d2e00",
        "inverse-primary": "#755b00",
        "on-primary-container": "#4b3a00",
        "primary": "#ecc246",
        "on-surface-variant": "#d1c5af",
        "tertiary-fixed": "#dbe1ff",
        "outline": "#99907b",
        "inverse-on-surface": "#2b3139",
        "on-tertiary-fixed-variant": "#244191",
        "on-surface": "#dde3ed",
        "secondary": "#ffb4aa",
        "surface-container-low": "#161c23"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "stack-sm": "8px",
        "stack-lg": "32px",
        "unit": "4px",
        "container-padding": "24px",
        "gutter": "16px",
        "stack-md": "16px"
      },
      "fontFamily": {
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "data-mono-lg": ["JetBrains Mono"],
        "data-mono-sm": ["JetBrains Mono"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"]
      },
      "fontSize": {
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "data-mono-lg": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "data-mono-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
